
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 30 00:00:49 ART 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int AND = 4;
  public static final int PLUS = 3;
  public static final int RBRACE = 18;
  public static final int OR = 5;
  public static final int RPAREN = 8;
  public static final int INT = 14;
  public static final int SEMI = 2;
  public static final int RETURN = 12;
  public static final int TRUE = 10;
  public static final int LBRACE = 17;
  public static final int LPAREN = 7;
  public static final int ID = 20;
  public static final int BOOLEAN = 15;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int MAIN = 13;
  public static final int FALSE = 11;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int VOID = 16;
}

